version: "3.8"

services:
  backend:
    build: ./backend
    image: backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb+srv://mrawais:awais1405@cluster0.qi9agsw.mongodb.net/mydatabase
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    image: frontend
    ports:
      - "4001:4000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
