name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Containers using Docker Compose
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

  # Run Unit Tests (Frontend and Backend)
  run-tests:
    runs-on: ubuntu-latest
    needs: [build-containers]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies and Run Tests for Frontend
        run: |
          cd frontend
          npm install
          npm test -- --coverage
      - name: Install Dependencies and Run Tests for Backend
        run: |
          cd backend
          npm install
          npm test -- --coverage

  # Linting and SAST for Frontend and Backend
  linting:
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js for Linting
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run Linter for Frontend
        run: |
          cd frontend
          npm install
          npm run lint
      - name: Run Linter for Backend
        run: |
          cd backend
          npm install
          npm run lint

  # Push Docker Containers to DockerHub
  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [build-containers]
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Tag and Push Frontend Image
        run: |
          docker tag devopsass_frontend:latest ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  
      - name: Tag and Push Backend Image
        run: |
          docker tag devopsass_backend:latest ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
  